<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>pep</string>
	</array>
	<key>name</key>
	<string>Pep8</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#strings</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#comment-single-line</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#variable</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#constant</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#storage</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#keyword</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#entity</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>character</key>
		<dict>
			<key>match</key>
			<string>('[^\\']'|'\\.')</string>
			<key>name</key>
			<string>string.character.pep8</string>
		</dict>
		<key>comment-single-line</key>
		<dict>
			<key>match</key>
			<string>;.*</string>
			<key>name</key>
			<string>comment.singleline.pep8</string>
		</dict>
		<key>comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment-single-line</string>
				</dict>
			</array>
		</dict>
		<key>constant</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>-?0(x|X)[0-9A-Fa-f]+</string>
					<key>name</key>
					<string>constant.numeric.hex.pep8</string>
				</dict>
				<dict>
					<key>match</key>
					<string>-?([0-9]+)</string>
					<key>name</key>
					<string>constant.numeric.int.pep8</string>
				</dict>
			</array>
		</dict>
		<key>entity</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>, *(i|d|x|n|(sx?f?))</string>
					<key>name</key>
					<string>entity.other.attribute-name.pep8</string>
				</dict>
				<dict>
					<key>match</key>
					<string>( |\t)*</string>
					<key>name</key>
					<string>entity.whitespaces.pep8</string>
				</dict>
			</array>
		</dict>
		<key>keyword</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>([cC][aA][lL][lL])|([sS][tT][oO][pP])|([bB][rR]((([lL]|[gG])([tT]|[eE]))|([eE][qQ])|([nN][eE])|[vV]|[cC])?)|([rR][eE][tT]([0-7]|([tT][rR])))\b</string>
					<key>name</key>
					<string>keyword.control.pep8</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(([aA][dD][dD])|([sS][uU][bB])|([nN][oO][tT])|([nN][eE][gG])|([aA][sS]([lL]|[rR]))|([rR][oO]([lL]|[rR]))|([oO][rR])|([cC][pP]))([aA]|[xX])\b</string>
					<key>name</key>
					<string>keyword.operator.pep8</string>
				</dict>
				<dict>
					<key>match</key>
					<string>([mM][oO][vV]([sS][pP]|[fF][lL][gG])[aA])|([nN][oO][pP][0-3]?)|((([aA][dD][dD])|([sS][uU][bB]))[sS][pP])|([dD][eE][cC]([iI]|[oO]))|((([lL][dD])|([sS][tT]))([bB][yY][tT][eE])?([aA]|[xX]))|([cC][hH][aA][rR]([iI]|[oO]))|([sS][tT][rR][oO])\b</string>
					<key>name</key>
					<string>keyword.misc.pep8</string>
				</dict>
			</array>
		</dict>
		<key>simple-string</key>
		<dict>
			<key>begin</key>
			<string>\"</string>
			<key>end</key>
			<string>\"</string>
			<key>name</key>
			<string>string.quoted.double.pep8</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>([^\\]|\\.)</string>
					<key>name</key>
					<string>string.char.pep8</string>
				</dict>
			</array>
		</dict>
		<key>storage</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>[.](([bB][uU][rR][nN])|([eE][qQ][uU][aA][tT][eE])|([bB][lL][oO][cC][kK])|([eE][nN][dD])|([bB][yY][tT][eE])|([wW][oO][rR][dD])|([aA][dD][dD][rR][sS][sS])|([aA][sS][cC][iI][iI]))</string>
					<key>name</key>
					<string>storage.type.pep8</string>
				</dict>
			</array>
		</dict>
		<key>strings</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#simple-string</string>
				</dict>
			</array>
		</dict>
		<key>variable</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>[a-z][a-zA-Z0-9_]* *[:]?</string>
					<key>name</key>
					<string>variable.other.pep8</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.pep8</string>
	<key>uuid</key>
	<string>b2423139-ebee-4453-bb51-74755ea62af4</string>
</dict>
</plist>
